#!/usr/bin/env python3
"""Generate the exact 48-case unequal-column table diagnostic campaign.

The campaign is intentionally materialized under ``target/`` rather than committed as
48 ordinary public corpus documents. Its checked-in lock binds the complete factorial
matrix and every generated byte, while ``RENDER_ORACLE.json`` reuses rwml's strict
external-render transport contract.

Usage:
    python3 scripts/generate_unequal_table_oracle.py
    python3 scripts/generate_unequal_table_oracle.py --check
    python3 scripts/generate_unequal_table_oracle.py --refresh-lock
"""

from __future__ import annotations

import argparse
import hashlib
import io
import itertools
import json
import os
import sys
import tempfile
import zipfile
from html import escape
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = Path(__file__).resolve()
DEFAULT_OUTPUT = ROOT / "target" / "render-oracle" / "unequal-table-v1"
DEFAULT_LOCK = ROOT / "corpus" / "public" / "oracle" / "unequal-table-v1.json"

CAMPAIGN = "unequal-table-continuation-v1"
LOCK_SCHEMA = "rwml.unequal-table-corpus-lock.v1"
CORPUS_SCHEMA = "rwml.render-oracle-corpus.v1"
LAYOUTS = ("equal", "narrow-wide", "three-progressive", "wide-narrow")
WIDTH_POLICIES = ("auto", "dxa", "pct")
FRAGMENT_CLASSES = ("row-boundary", "split-row")
HANDOFF_CLASSES = ("column", "page")

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
RELS_CT = "application/vnd.openxmlformats-package.relationships+xml"
MAIN_CT = (
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"
)
STYLES_CT = (
    "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
)
XML_DECL = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'

PROVENANCE = """# Unequal-column table diagnostic corpus provenance

All 48 DOCX inputs are generated from repository-owned raw OOXML by
`scripts/generate_unequal_table_oracle.py`. The generator fixes package member order,
timestamps, platform metadata, page geometry, section columns, table geometry, text,
and the requested Noto Sans font family. Inputs contain synthetic ASCII tokens only;
no private or third-party document content is present.

The generated documents and metadata are licensed under the repository's MIT license.
The checked-in `corpus/public/oracle/unequal-table-v1.json` file binds every generated
input by byte length and SHA-256. `RENDER_ORACLE.json` is the strict campaign manifest
consumed by rwml's external-validation tooling.
"""


class Case:
    __slots__ = (
        "case_id",
        "layout",
        "width_policy",
        "fragment",
        "handoff",
        "index",
    )

    def __init__(
        self,
        *,
        case_id: str,
        layout: str,
        width_policy: str,
        fragment: str,
        handoff: str,
        index: int,
    ) -> None:
        self.case_id = case_id
        self.layout = layout
        self.width_policy = width_policy
        self.fragment = fragment
        self.handoff = handoff
        self.index = index

    @property
    def relative_path(self) -> str:
        return f"documents/{self.case_id}.docx"

    @property
    def column_count(self) -> int:
        return 3 if self.layout == "three-progressive" else 2

    @property
    def expected_pages(self) -> int:
        return 2 if self.handoff == "page" else 1


def _cases() -> tuple[Case, ...]:
    values = sorted(
        (
            f"{layout}-{width_policy}-{fragment}-{handoff}",
            layout,
            width_policy,
            fragment,
            handoff,
        )
        for layout, width_policy, fragment, handoff in itertools.product(
            LAYOUTS, WIDTH_POLICIES, FRAGMENT_CLASSES, HANDOFF_CLASSES
        )
    )
    return tuple(
        Case(
            case_id=case_id,
            layout=layout,
            width_policy=width_policy,
            fragment=fragment,
            handoff=handoff,
            index=index,
        )
        for index, (case_id, layout, width_policy, fragment, handoff) in enumerate(
            values
        )
    )


CASES = _cases()


def _canonical_json(value: object) -> bytes:
    return (
        json.dumps(value, ensure_ascii=True, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")


def _zip(parts: Iterable[tuple[str, bytes]]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, payload in parts:
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.compress_type = zipfile.ZIP_STORED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, payload)
    return buffer.getvalue()


def _relationships(entries: Iterable[tuple[str, str, str]]) -> bytes:
    body = "".join(
        f'<Relationship Id="{identifier}" Type="{relationship_type}" '
        f'Target="{target}"/>'
        for identifier, relationship_type, target in entries
    )
    return (
        XML_DECL
        + '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        + body
        + "</Relationships>"
    ).encode("utf-8")


def _content_types() -> bytes:
    return (
        XML_DECL
        + '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        f'<Default Extension="rels" ContentType="{RELS_CT}"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        f'<Override PartName="/word/document.xml" ContentType="{MAIN_CT}"/>'
        f'<Override PartName="/word/styles.xml" ContentType="{STYLES_CT}"/>'
        "</Types>"
    ).encode("utf-8")


def _styles() -> bytes:
    return (
        XML_DECL
        + f'<w:styles xmlns:w="{W}">'
        "<w:docDefaults><w:rPrDefault><w:rPr>"
        '<w:rFonts w:ascii="Noto Sans" w:hAnsi="Noto Sans" '
        'w:eastAsia="Noto Sans" w:cs="Noto Sans"/>'
        '<w:sz w:val="16"/><w:szCs w:val="16"/>'
        "</w:rPr></w:rPrDefault><w:pPrDefault><w:pPr>"
        '<w:spacing w:before="0" w:after="0" w:line="200" w:lineRule="exact"/>'
        "</w:pPr></w:pPrDefault></w:docDefaults>"
        '<w:style w:type="paragraph" w:default="1" w:styleId="Normal">'
        '<w:name w:val="Normal"/></w:style>'
        "</w:styles>"
    ).encode("utf-8")


def _paragraph(text: str) -> str:
    return f"<w:p><w:r><w:t>{escape(text)}</w:t></w:r></w:p>"


def _column_break() -> str:
    return '<w:p><w:r><w:br w:type="column"/></w:r></w:p>'


def _column_markup(case: Case) -> str:
    if case.layout == "equal":
        return '<w:cols w:num="2" w:equalWidth="1" w:space="360"/>'
    columns = {
        "narrow-wide": ((1800, 360), (3600, None)),
        "wide-narrow": ((3600, 360), (1800, None)),
        "three-progressive": ((1200, 240), (1680, 240), (2400, None)),
    }[case.layout]
    children = "".join(
        f'<w:col w:w="{width}"'
        + (f' w:space="{space}"' if space is not None else "")
        + "/>"
        for width, space in columns
    )
    return (
        f'<w:cols w:num="{len(columns)}" w:equalWidth="0">'
        + children
        + "</w:cols>"
    )


def _table_width_markup(width_policy: str) -> tuple[str, str, str]:
    if width_policy == "auto":
        return (
            '<w:tblW w:w="0" w:type="auto"/>',
            '<w:tblGrid><w:gridCol w:w="800"/><w:gridCol w:w="800"/></w:tblGrid>',
            '<w:tcW w:w="0" w:type="auto"/>',
        )
    if width_policy == "dxa":
        return (
            '<w:tblW w:w="2400" w:type="dxa"/><w:tblLayout w:type="fixed"/>',
            '<w:tblGrid><w:gridCol w:w="1200"/><w:gridCol w:w="1200"/></w:tblGrid>',
            '<w:tcW w:w="1200" w:type="dxa"/>',
        )
    if width_policy == "pct":
        return (
            '<w:tblW w:w="5000" w:type="pct"/><w:tblLayout w:type="fixed"/>',
            '<w:tblGrid><w:gridCol w:w="2880"/><w:gridCol w:w="2880"/></w:tblGrid>',
            '<w:tcW w:w="2500" w:type="pct"/>',
        )
    raise ValueError(f"unknown width policy: {width_policy}")


def _table_borders() -> str:
    border = 'w:val="single" w:sz="8" w:space="0" w:color="000000"'
    return (
        "<w:tblBorders>"
        + "".join(
            f"<w:{edge} {border}/>"
            for edge in ("top", "left", "bottom", "right", "insideH", "insideV")
        )
        + "</w:tblBorders>"
    )


def _cell(paragraphs: Iterable[str], cell_width: str) -> str:
    return (
        "<w:tc><w:tcPr>"
        + cell_width
        + "</w:tcPr>"
        + "".join(paragraphs)
        + "</w:tc>"
    )


def _table(case: Case) -> str:
    table_width, grid, cell_width = _table_width_markup(case.width_policy)
    table_properties = (
        "<w:tblPr>"
        + table_width
        + _table_borders()
        + '<w:tblCellMar><w:top w:w="20" w:type="dxa"/>'
        '<w:left w:w="20" w:type="dxa"/><w:bottom w:w="20" w:type="dxa"/>'
        '<w:right w:w="20" w:type="dxa"/></w:tblCellMar>'
        + "</w:tblPr>"
    )
    if case.fragment == "row-boundary":
        rows = []
        for row in range(1, 21):
            left = _cell([_paragraph(f"T{case.index:02d}L{row:02d}")], cell_width)
            right = _cell([_paragraph(f"T{case.index:02d}R{row:02d}")], cell_width)
            rows.append("<w:tr>" + left + right + "</w:tr>")
    elif case.fragment == "split-row":
        left = _cell(
            (_paragraph(f"T{case.index:02d}L{line:02d}") for line in range(1, 27)),
            cell_width,
        )
        right = _cell(
            (_paragraph(f"T{case.index:02d}R{line:02d}") for line in range(1, 27)),
            cell_width,
        )
        rows = ["<w:tr>" + left + right + "</w:tr>"]
    else:
        raise ValueError(f"unknown fragment class: {case.fragment}")
    return "<w:tbl>" + table_properties + grid + "".join(rows) + "</w:tbl>"


def build_document(case: Case) -> bytes:
    body = [_paragraph(f"CASE-{case.index:02d}")]
    if case.handoff == "page":
        body.extend(_column_break() for _ in range(case.column_count - 1))
    body.extend(_paragraph(f"F{case.index:02d}-{line:02d}") for line in range(1, 7))
    body.append(_table(case))
    body.append(
        '<w:sectPr><w:pgSz w:w="7200" w:h="7200"/>'
        '<w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/>'
        + _column_markup(case)
        + "</w:sectPr>"
    )
    document = (
        XML_DECL
        + f'<w:document xmlns:w="{W}"><w:body>'
        + "".join(body)
        + "</w:body></w:document>"
    ).encode("utf-8")
    return _zip(
        (
            ("[Content_Types].xml", _content_types()),
            (
                "_rels/.rels",
                _relationships((("rId1", f"{R}/officeDocument", "word/document.xml"),)),
            ),
            ("word/document.xml", document),
            (
                "word/_rels/document.xml.rels",
                _relationships((("rIdStyles", f"{R}/styles", "styles.xml"),)),
            ),
            ("word/styles.xml", _styles()),
        )
    )


def _document_records() -> list[dict[str, Any]]:
    records = []
    for case in CASES:
        payload = build_document(case)
        records.append(
            {
                "id": case.case_id,
                "path": case.relative_path,
                "format": "docx",
                "bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest(),
                "layout": case.layout,
                "width_policy": case.width_policy,
                "fragment": case.fragment,
                "handoff": case.handoff,
                "columns": case.column_count,
                "expected_pages": case.expected_pages,
            }
        )
    return records


def corpus_root_sha256(documents: Iterable[dict[str, Any]]) -> str:
    digest = hashlib.sha256()
    for document in documents:
        for value in (
            document["id"],
            document["path"],
            document["format"],
            str(document["bytes"]),
            document["sha256"],
        ):
            encoded = str(value).encode("utf-8")
            digest.update(len(encoded).to_bytes(8, "little"))
            digest.update(encoded)
    return digest.hexdigest()


def _feature_labels(record: dict[str, Any]) -> list[str]:
    labels = {
        f"columns-{record['columns']}",
        "columns-equal" if record["layout"] == "equal" else "columns-unequal",
        f"handoff-{record['handoff']}",
        f"layout-{record['layout']}",
        f"table-fragment-{record['fragment']}",
        "table-continuation",
        f"table-width-{record['width_policy']}",
    }
    return sorted(labels)


def _strict_manifest(records: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "schema": CORPUS_SCHEMA,
        "campaign": CAMPAIGN,
        "limits": {
            "max_documents": 48,
            "max_input_bytes": 1024 * 1024,
            "max_total_input_bytes": 64 * 1024 * 1024,
            "max_pages_per_document": 8,
        },
        "provenance": [
            {
                "id": "synthetic-unequal-table",
                "kind": "generated",
                "license": "MIT",
                "reference": "PROVENANCE.md",
            }
        ],
        "documents": [
            {
                "id": record["id"],
                "path": record["path"],
                "format": record["format"],
                "bytes": record["bytes"],
                "sha256": record["sha256"],
                "provenance": "synthetic-unequal-table",
                "features": _feature_labels(record),
                "expected": {
                    "pages": record["expected_pages"],
                    "warnings": [],
                },
            }
            for record in records
        ],
    }


def campaign_artifacts() -> dict[str, bytes]:
    records = _document_records()
    artifacts = {
        case.relative_path: build_document(case)
        for case in CASES
    }
    artifacts["PROVENANCE.md"] = PROVENANCE.encode("utf-8")
    artifacts["RENDER_ORACLE.json"] = _canonical_json(_strict_manifest(records))
    return artifacts


def _lock_value() -> dict[str, Any]:
    records = _document_records()
    return {
        "schema": LOCK_SCHEMA,
        "campaign": CAMPAIGN,
        "generator": {
            "path": SCRIPT_PATH.relative_to(ROOT).as_posix(),
            "sha256": hashlib.sha256(SCRIPT_PATH.read_bytes()).hexdigest(),
        },
        "matrix": {
            "layouts": list(LAYOUTS),
            "width_policies": list(WIDTH_POLICIES),
            "fragment_classes": list(FRAGMENT_CLASSES),
            "handoff_classes": list(HANDOFF_CLASSES),
        },
        "corpus_root_sha256": corpus_root_sha256(records),
        "documents": records,
    }


def _atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def refresh_lock(path: Path = DEFAULT_LOCK) -> None:
    _atomic_write(path, _canonical_json(_lock_value()))


def verify_lock(path: Path = DEFAULT_LOCK) -> None:
    expected = _canonical_json(_lock_value())
    try:
        actual = path.read_bytes()
    except FileNotFoundError as error:
        raise ValueError(f"missing unequal-table corpus lock: {path}") from error
    if actual != expected:
        raise ValueError(
            "unequal-table corpus lock is stale: "
            f"expected {hashlib.sha256(expected).hexdigest()}, "
            f"found {hashlib.sha256(actual).hexdigest()}"
        )


def _validate_output_root(output: Path) -> None:
    if output.is_symlink():
        raise ValueError(f"output directory must not be a symlink: {output}")
    if output.exists() and not output.is_dir():
        raise ValueError(f"output path is not a directory: {output}")


def materialize(output: Path, *, lock_path: Path = DEFAULT_LOCK) -> None:
    verify_lock(lock_path)
    _validate_output_root(output)
    output.mkdir(parents=True, exist_ok=True)
    for relative_path, payload in sorted(campaign_artifacts().items()):
        destination = output / relative_path
        if destination.is_symlink():
            raise ValueError(f"generated output must not be a symlink: {destination}")
        _atomic_write(destination, payload)


def check_materialized(output: Path, *, lock_path: Path = DEFAULT_LOCK) -> bool:
    try:
        verify_lock(lock_path)
        _validate_output_root(output)
    except ValueError as error:
        print(f"generate_unequal_table_oracle: {error}", file=sys.stderr)
        return False
    expected = campaign_artifacts()
    valid = True
    for relative_path, payload in sorted(expected.items()):
        path = output / relative_path
        try:
            actual = path.read_bytes()
        except (OSError, ValueError):
            print(f"missing generated artifact: {path}", file=sys.stderr)
            valid = False
            continue
        if path.is_symlink() or actual != payload:
            print(f"stale generated artifact: {path}", file=sys.stderr)
            valid = False
    documents = output / "documents"
    if documents.is_dir():
        expected_docx = {
            (output / relative_path).resolve()
            for relative_path in expected
            if relative_path.endswith(".docx")
        }
        for path in documents.rglob("*.docx"):
            if path.resolve() not in expected_docx:
                print(f"unexpected generated document: {path}", file=sys.stderr)
                valid = False
    return valid


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the digest-locked unequal-column table oracle campaign."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--check", action="store_true")
    action.add_argument("--refresh-lock", action="store_true")
    args = parser.parse_args(argv)

    try:
        if args.refresh_lock:
            refresh_lock(args.lock)
            verify_lock(args.lock)
            print(f"wrote {args.lock}")
            return 0
        if args.check:
            return 0 if check_materialized(args.output, lock_path=args.lock) else 1
        materialize(args.output, lock_path=args.lock)
    except (OSError, ValueError) as error:
        print(f"generate_unequal_table_oracle: {error}", file=sys.stderr)
        return 1
    print(f"wrote 48 documents and strict metadata beneath {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
